version: 1.0
stages:
  build:
    image: docker:latest
    scripts:
    - ./scripts/build.sh
  test:
    image: ruby:3.2
    scripts:
    - ./scripts/test.sh
  release:
    image: ruby:3.2
    scripts:
    - ./scripts/release.sh
    - ./scripts/publish.sh
    only:
    - main
