plugins:
- rubocop-rake
- rubocop-rspec

Layout/LineLength:
  Max: 100

AllCops:
  TargetRubyVersion: 3.4
  Exclude:
  - 'db/schema.rb'
  - 'vendor/**/*'
  - 'tmp/**/*'
  - Itsi.rb
  NewCops: enable

Metrics/AbcSize:
  Max: 21

Metrics/BlockLength:
  Max: 35
  Exclude:
  - 'spec/**/*_spec.rb'
  - 'Rakefile'
  - '*.gemspec'

Metrics/MethodLength:
  Max: 20

Metrics/ModuleLength:
  Max: 165
  Exclude:
  - 'spec/**/*_spec.rb'

Metrics/ClassLength:
  Max: 300
  Exclude:
  - 'spec/**/*_spec.rb'

Gemspec/RequireMFA:
  Enabled: false

Style/MixinUsage:
  Exclude:
  - "bin/console"

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringConcatenation:
  Exclude:
  - 'Rakefile'

RSpec/NamedSubject:
  Enabled: false

RSpec/BeforeAfterAll:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 12

# For now, this is disabled until I can go through all the specs and fix them
RSpec/MultipleExpectations:
  Max: 13

RSpec/ExampleLength:
  Max: 34

Gemspec/DevelopmentDependencies:
  Enabled: false
