language: ruby
cache: bundler
rvm:
- 2.6
- 2.7
before_install: gem install bundler -v 2.1.4
deploy:
  provider: rubygems
  api_key:
    secure: PqnibRsu5Gz3x3EhiWryUCx40RDTXwm+Zl4QA7XAtQNY9TAzjlzeIHaUhLwZwXuF8tN6MNVW+2XRKzIV+wCaxUqUISyj0rSv5giSrvCej4f89E6m2N00f38Tj6YjDDdCfw34/HASZldRgOJ/eW/Z8OAKHWGmcxImzD/OHgNjvBsEW11aLO/RaDERSbAk7srXbEwaCR+GYhRco+ynjR/EbqZ1Visf+CVdPPn0lgIWuHCiBXL8zLCHSyKNkUvDE13mjS+hY27bdD6au6Ad6ACm3hj2UyjVG0xcsVqw0XCr4dLc3JSaNgAqh4HtY0wWEouKDw2lWYihvw8eAUcw+uNfdrf3WpcVvfUeHm17UyZSy1EHujIVENMEeb8OpfT4zRPeTYC9ShzsdLhAY4plD1nNBwVESkYxy3wJdxB2UIa6X8M/+gO/SDbuOmGkXJJ05ccOrucIB23xfa4qDmRfsakAcYZ9o17dCKP3WMYuAz+071E2ZF4zDXu8aNmS1gcx6uu5sei4JAFHTRSMJuNvV0H9CS2slMOLCuF2nPf94CjIG5JrXWQcHM6GdhgRpMqU3T9yW6jn5SCElfoiR6sQEi5zoLphYD8zzf1QPPG/37S+6Uail/00vTJbuCZuFLcKMMjwmoW6ZqSFtsCK/h7eFndR6mMFnDB2lAC9LByW9cVFDpo=
  gem: bullion
  on:
    tags: true
    repo: jgnagy/bullion
  skip_cleanup: 'true'
